basePath: /
consumes:
- application/json
definitions:
  model.DictReadReq:
    properties:
      groupKeys:
        description: 需要查询的字典分组
        example:
        - serviceCode
        - responseType
        items:
          type: string
        type: array
    required:
    - groupKeys
    type: object
  model.DictReadRes:
    properties:
      list:
        additionalProperties:
          items:
            $ref: '#/definitions/model.SelectRes'
          type: array
        description: 字典下拉列表 {'serviceCode':"[{'label':'基础','value':'1'}]"}
        type: object
      map:
        additionalProperties:
          additionalProperties:
            type: string
          type: object
        description: 字典翻译Map {'serviceCode':{'1':'基础'}}
        type: object
    type: object
  model.DocsAuthLg:
    properties:
      code:
        description: 响应码
        example: E0002
        type: string
      msg:
        description: 响应消息
        example: 当前尚未登陆
        type: string
    type: object
  model.DocsAuthNg:
    properties:
      code:
        description: 响应码
        example: E0003
        type: string
      msg:
        description: 响应消息
        example: 当前接口禁止访问
        type: string
    type: object
  model.DocsErr:
    properties:
      code:
        description: 响应码
        example: E0000
        type: string
      msg:
        description: 响应消息
        example: 系统异常
        type: string
    type: object
  model.DocsOk:
    properties:
      code:
        description: 响应码
        example: S0X0X/F0X0X
        type: string
      data:
        description: 响应数据
        example: 响应数据
        type: string
      msg:
        description: 响应消息
        example: 操作成功/失败
        type: string
      unPop:
        description: 免弹窗提示
        example: true
        type: boolean
    type: object
  model.DocsReq:
    properties:
      httpCode:
        description: 响应HTTPCode，不传默认响应200，支持200/400/401/403/500
        example: 200
        type: integer
    type: object
  model.DocsVail:
    properties:
      code:
        description: 响应码
        example: E0001
        type: string
      msg:
        description: 响应消息
        example: xx字段应该为必填
        type: string
    type: object
  model.ResBody:
    properties:
      code:
        description: 响应码
        example: S0000/F0000
        type: string
      data:
        description: 响应数据
      msg:
        description: 响应消息
        example: 操作成功/失败
        type: string
      unPop:
        description: 免弹窗提示
        example: true
        type: boolean
    type: object
  model.SelectRes:
    properties:
      label:
        description: 展示名
        example: 展示名
        type: string
      value:
        description: 展示值
        example: 展示值
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: dev@siteol.com
    name: smart
    url: https://smart.siteol.com
  description: "![Smart](/docs/file/logo.png)\r\n\r\n# 概述\r\n\r\n轻量易用的授权基座smart，提供一个非官方RBAC授权模型的基础开箱即用中台管理服务。\r\n\r\n支持响应码自定义国际化、高粒度权限分配、接口路由配置和实时生效，同时支持部门数据权限横向访问限制。\r\n\r\n本系统的全部接口采用【POST】【application/json】方式传输数据。\r\n\r\n除开放接口以外的其他接口均需要通过【ApiKeyAuth:请求头[Token]】完成鉴权。\r\n\r\n系统技术栈：Golang、VueNext、MySQL、Redis、Gin、ArcoDesign\r\n\r\n#
    接口文档\r\n\r\n轻度依赖集成，通过静态HTML加载yaml文件进行打开接口文档。\r\n\r\n该接口文档提供Swagger[支持调试]和ReDoc[阅读增强]两个版本。\r\n\r\n[Swagger[支持调试]：/docs/swagger/index.html](http://localhost:8000/docs/swagger/index.html)
    丨 [ReDoc[阅读增强]：/docs/redoc/index.html](http://localhost:8000/docs/redoc/index.html)\r\n\r\n##
    生成说明\r\n\r\n- 首次集成\r\n\r\ngo install github.com/swaggo/swag/cmd/swag@latest\r\n\r\n-
    初始化swagger.yaml文件\r\n\r\nswag init\r\n\r\n- 如果像本工程一样依赖了api.md文件描述项目\r\n\r\nswag
    init --md .\r\n\r\n- 删除多余的生成\r\n\r\nrm .\\docs\\docs.go\r\n\r\n删除docs.go是因为本项目中并未采用下述依赖来集成。\r\n\r\n而是通过HTML模板+JS+YAML引入集成，移除docs.go用于避免依赖编译报错。\r\n\r\n-
    github.com/swaggo/swag\r\n- github.com/swaggo/gin-swagger\r\n- github.com/swaggo/files\r\n\r\n源帮助页：[https://github.com/swaggo/swag/blob/master/README_zh-CN.md](https://github.com/swaggo/swag/blob/master/README_zh-CN.md)\r\n"
  title: smart
  version: "1.0"
  x-logo:
    altText: smart
    url: /docs/file/logo.png
paths:
  /docs/sample:
    post:
      consumes:
      - application/json
      description: 系统API基本示例
      operationId: Sample示例
      parameters:
      - description: 示例请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.DocsReq'
      produces:
      - application/json
      responses:
        "200":
          description: 业务受理成功
          schema:
            $ref: '#/definitions/model.DocsOk'
        "400":
          description: 数据校验失败
          schema:
            $ref: '#/definitions/model.DocsVail'
        "401":
          description: 当前尚未登陆
          schema:
            $ref: '#/definitions/model.DocsAuthLg'
        "403":
          description: 权限校验失败
          schema:
            $ref: '#/definitions/model.DocsAuthNg'
        "500":
          description: 服务系统异常
          schema:
            $ref: '#/definitions/model.DocsErr'
      security:
      - Token: []
      summary: 通用API示例
      tags:
      - 开放接口
  /plat/dict/read:
    post:
      consumes:
      - application/json
      description: 获取字典下拉列表以及关联键值Map
      operationId: ReadDict读取字典
      parameters:
      - description: 语言，不传默认为zh-CN
        in: header
        name: Lang
        type: string
      - description: 请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.DictReadReq'
      produces:
      - application/json
      responses:
        "200":
          description: 响应成功
          schema:
            allOf:
            - $ref: '#/definitions/model.ResBody'
            - properties:
                data:
                  $ref: '#/definitions/model.DictReadRes'
              type: object
      security:
      - Token: []
      summary: 读取字典
      tags:
      - 数据字典
  /plat/dictGroup/list:
    post:
      consumes:
      - application/json
      description: 获取字典分组列表，改列表为内置列表
      operationId: ListDictGroup字典分组列表
      parameters:
      - description: 语言，不传默认为zh-CN
        in: header
        name: Lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 响应成功
          schema:
            allOf:
            - $ref: '#/definitions/model.ResBody'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.SelectRes'
                  type: array
              type: object
      security:
      - Token: []
      summary: 字典分组列表
      tags:
      - 数据字典
securityDefinitions:
  Token:
    in: header
    name: Token
    type: apiKey
swagger: "2.0"
tags:
- description: 基础开发接口
  name: 开放接口
x-tagGroups:
- name: 基础
  tags:
  - 开放接口
- name: 平台
  tags:
  - 租户管理
  - 集团部门
  - 角色配置
  - 登陆账号
  - 访问权限
  - 路由接口
  - 响应文言
  - 数据字典
