basePath: /
consumes:
- application/json
definitions:
  baseModel.IdReq:
    properties:
      id:
        description: 数据ID
        example: 1
        type: integer
    type: object
  baseModel.PageRes:
    properties:
      list:
        description: 分页数据
      total:
        description: 数据总量
        type: integer
    type: object
  baseModel.ResBody:
    properties:
      code:
        description: 响应码
        example: S0000/F0000
        type: string
      data:
        description: 响应数据
      msg:
        description: 响应消息
        example: 操作成功/失败
        type: string
      unPop:
        description: 免弹窗提示
        example: true
        type: boolean
    type: object
  baseModel.SelectRes:
    properties:
      label:
        description: 展示名
        example: 展示名
        type: string
      value:
        description: 展示值
        example: 展示值
        type: string
    type: object
  baseModel.SortReq:
    properties:
      id:
        description: 数据ID
        example: 1
        type: integer
      sort:
        description: 序号
        example: 1
        type: integer
    required:
    - id
    type: object
  baseModel.SortRes:
    properties:
      id:
        description: 默认数据ID
        example: 1
        type: integer
      name:
        description: 权限名称，界面展示，建议与界面导航一致
        example: 账号管理
        type: string
      sort:
        description: 权限排序
        example: 1
        type: integer
    type: object
  model.DictAddReq:
    properties:
      choose:
        description: 是否可被选择 0可选择 1不可选择
        example: "0"
        type: string
      groupKey:
        description: 字典分组KEY
        example: serviceCode
        type: string
      label:
        description: 字段名称
        example: 平台基础
        type: string
      labelEn:
        description: 字段名称（英文）
        example: PlatBase
        type: string
      remark:
        description: 字典描述
        example: 业务类型字典
        type: string
      val:
        description: 字典值（字符型）
        example: "1"
        type: string
    required:
    - choose
    - groupKey
    - label
    - labelEn
    - val
    type: object
  model.DictBroReq:
    properties:
      groupKey:
        description: 字典分组KEY
        example: serviceCode
        type: string
    required:
    - groupKey
    type: object
  model.DictEditReq:
    properties:
      choose:
        description: 是否可被选择 0可选择 1不可选择
        example: "0"
        type: string
      id:
        description: 数据ID
        example: 1
        type: integer
      label:
        description: 字段名称
        example: 平台基础
        type: string
      labelEn:
        description: 字段名称（英文）
        example: PlatBase
        type: string
      remark:
        description: 字典描述
        example: 业务类型字典
        type: string
    required:
    - choose
    - id
    - label
    - labelEn
    type: object
  model.DictGroupReadRes:
    properties:
      list:
        description: 字典分组下拉列表 [{'label':'业务模块','value':'serviceCode'}]
        items:
          $ref: '#/definitions/baseModel.SelectRes'
        type: array
      map:
        additionalProperties:
          type: string
        description: 字典分组翻译Map
        example:
          '{''serviceCode''': '''业务模块''}'
        type: object
    type: object
  model.DictNextValReq:
    properties:
      groupKey:
        description: 字典分组KEY
        example: serviceCode
        type: string
    required:
    - groupKey
    type: object
  model.DictPageReq:
    properties:
      current:
        description: 当前页
        example: 1
        type: integer
      groupKey:
        description: 需要查询的字典分组
        example: serviceCode
        type: string
      label:
        description: 字典展示文言，跟随请求语言模糊检索
        example: 成功
        type: string
      pageSize:
        description: 单页数量
        example: 10
        type: integer
    type: object
  model.DictPageRes:
    properties:
      choose:
        description: 是否可被选择 0可选择 1不可选择
        example: "1"
        type: string
      groupKey:
        description: 字典分组KEY
        example: serviceCode
        type: string
      id:
        description: 数据ID
        example: 1
        type: integer
      label:
        description: 字段名称
        example: 平台
        type: string
      labelEn:
        description: 字段名称（英文）
        example: Plat
        type: string
      mark:
        description: 变更标识 0可变更 1禁止变更
        example: "1"
        type: string
      remark:
        description: 字典描述
        example: 业务编码：平台
        type: string
      sort:
        description: 字典排序
        example: 0
        type: integer
      val:
        description: 字典值（字符型）
        example: "1"
        type: string
    type: object
  model.DictReadReq:
    properties:
      groupKeys:
        description: 需要查询的字典分组
        example:
        - serviceCode
        - responseType
        items:
          type: string
        type: array
    required:
    - groupKeys
    type: object
  model.DictReadRes:
    properties:
      list:
        additionalProperties:
          items:
            $ref: '#/definitions/baseModel.SelectRes'
          type: array
        description: 字典下拉列表 {'serviceCode':"[{'label':'基础','value':'1'}]"}
        type: object
      map:
        additionalProperties:
          additionalProperties:
            type: string
          type: object
        description: 字典翻译Map {'serviceCode':{'1':'基础'}}
        type: object
    type: object
  model.DocsAuthLg:
    properties:
      code:
        description: 响应码
        example: E0002
        type: string
      msg:
        description: 响应消息
        example: 当前尚未登陆
        type: string
    type: object
  model.DocsAuthNg:
    properties:
      code:
        description: 响应码
        example: E0003
        type: string
      msg:
        description: 响应消息
        example: 当前接口禁止访问
        type: string
    type: object
  model.DocsErr:
    properties:
      code:
        description: 响应码
        example: E0000
        type: string
      msg:
        description: 响应消息
        example: 系统异常
        type: string
    type: object
  model.DocsOk:
    properties:
      code:
        description: 响应码
        example: S0X0X/F0X0X
        type: string
      data:
        description: 响应数据
        example: 响应数据
        type: string
      msg:
        description: 响应消息
        example: 操作成功/失败
        type: string
      unPop:
        description: 免弹窗提示
        example: true
        type: boolean
    type: object
  model.DocsReq:
    properties:
      httpCode:
        description: 响应HTTPCode，不传默认响应200，支持200/400/401/403/500
        example: 200
        type: integer
    type: object
  model.DocsVail:
    properties:
      code:
        description: 响应码
        example: E0001
        type: string
      msg:
        description: 响应消息
        example: xx字段应该为必填
        type: string
    type: object
  platDb.Dict:
    properties:
      choose:
        description: 是否可被选择 0可选择 1不可选择
        type: string
      createAt:
        description: 创建时间
        type: string
      groupKey:
        description: 字典分组KEY
        type: string
      id:
        description: 数据ID
        type: integer
      label:
        description: 字段名称
        type: string
      labelEn:
        description: 字段名称（英文）
        type: string
      mark:
        description: 变更标识 0可变更/登陆成功 1禁止变更/登陆失败
        type: string
      pid:
        description: 父级字典ID 默认 1（根数据）
        type: integer
      remark:
        description: 字典描述
        type: string
      sort:
        description: 字典排序
        type: integer
      status:
        description: 状态 0正常 1锁定 2封存
        type: string
      updateAt:
        description: 更新时间
        type: string
      val:
        description: 字典值（字符型）
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: dev@siteol.com
    name: smart
    url: https://smart.siteol.com
  description: "![Smart](/docs/file/logo.png)\r\n\r\n# 概述\r\n\r\n轻量易用的授权基座smart，提供一个非官方RBAC授权模型的基础开箱即用中台管理服务。\r\n\r\n支持响应码自定义国际化、高粒度权限分配、接口路由配置和实时生效，同时支持部门数据权限横向访问限制。\r\n\r\n本系统的全部接口采用【POST】【application/json】方式传输数据。\r\n\r\n除开放接口以外的其他接口均需要通过【ApiKeyAuth:请求头[Token]】完成鉴权。\r\n\r\n系统技术栈：Golang、VueNext、MySQL、Redis、Gin、ArcoDesign\r\n\r\n#
    接口文档\r\n\r\n轻度依赖集成，通过静态HTML加载yaml文件进行打开接口文档。\r\n\r\n该接口文档提供Swagger[支持调试]和ReDoc[阅读增强]两个版本。\r\n\r\n[Swagger[支持调试]：/docs/swagger/index.html](http://localhost:8000/docs/swagger/index.html)
    丨 [ReDoc[阅读增强]：/docs/redoc/index.html](http://localhost:8000/docs/redoc/index.html)\r\n\r\n##
    生成说明\r\n\r\n- 首次集成\r\n\r\ngo install github.com/swaggo/swag/cmd/swag@latest\r\n\r\n-
    初始化swagger.yaml文件\r\n\r\nswag init\r\n\r\n- 如果像本工程一样依赖了api.md文件描述项目\r\n\r\nswag
    init --md .\r\n\r\n- 删除多余的生成\r\n\r\nrm .\\docs\\docs.go\r\n\r\n删除docs.go是因为本项目中并未采用下述依赖来集成。\r\n\r\n而是通过HTML模板+JS+YAML引入集成，移除docs.go用于避免依赖编译报错。\r\n\r\n-
    github.com/swaggo/swag\r\n- github.com/swaggo/gin-swagger\r\n- github.com/swaggo/files\r\n\r\n源帮助页：[https://github.com/swaggo/swag/blob/master/README_zh-CN.md](https://github.com/swaggo/swag/blob/master/README_zh-CN.md)\r\n"
  title: smart
  version: "1.0"
  x-logo:
    altText: smart
    url: /docs/file/logo.png
paths:
  /docs/sample:
    post:
      consumes:
      - application/json
      description: 系统API基本示例
      operationId: Sample示例
      parameters:
      - description: 示例请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.DocsReq'
      produces:
      - application/json
      responses:
        "200":
          description: 业务受理成功
          schema:
            $ref: '#/definitions/model.DocsOk'
        "400":
          description: 数据校验失败
          schema:
            $ref: '#/definitions/model.DocsVail'
        "401":
          description: 当前尚未登陆
          schema:
            $ref: '#/definitions/model.DocsAuthLg'
        "403":
          description: 权限校验失败
          schema:
            $ref: '#/definitions/model.DocsAuthNg'
        "500":
          description: 服务系统异常
          schema:
            $ref: '#/definitions/model.DocsErr'
      security:
      - Token: []
      summary: 通用API示例
      tags:
      - 开放接口
  /plat/dict/add:
    post:
      consumes:
      - application/json
      description: 在字典分组下新建字典
      operationId: AddDict 字典新建
      parameters:
      - description: 请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.DictAddReq'
      produces:
      - application/json
      responses:
        "200":
          description: 响应成功
          schema:
            allOf:
            - $ref: '#/definitions/baseModel.ResBody'
            - properties:
                data:
                  type: boolean
              type: object
      security:
      - Token: []
      summary: 字典新建
      tags:
      - 数据字典
  /plat/dict/bro:
    post:
      consumes:
      - application/json
      description: 获取字典排序数据
      operationId: BroDict 字典排序数据
      parameters:
      - description: 语言，不传默认为zh-CN
        in: header
        name: Lang
        type: string
      - description: 请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.DictBroReq'
      produces:
      - application/json
      responses:
        "200":
          description: 响应成功
          schema:
            allOf:
            - $ref: '#/definitions/baseModel.ResBody'
            - properties:
                data:
                  $ref: '#/definitions/baseModel.SortRes'
              type: object
      security:
      - Token: []
      summary: 排序数据
      tags:
      - 数据字典
  /plat/dict/del:
    post:
      consumes:
      - application/json
      description: 字典封存处理
      operationId: DelDict 字典封存
      parameters:
      - description: 语言，不传默认为zh-CN
        in: header
        name: Lang
        type: string
      - description: 请求
        in: body
        name: req
        required: true
        schema:
          items:
            $ref: '#/definitions/baseModel.IdReq'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 响应成功
          schema:
            allOf:
            - $ref: '#/definitions/baseModel.ResBody'
            - properties:
                data:
                  type: boolean
              type: object
      security:
      - Token: []
      summary: 字典封存
      tags:
      - 数据字典
  /plat/dict/edit:
    post:
      consumes:
      - application/json
      description: 在字典分组下编辑字典
      operationId: EditDict 字典编辑
      parameters:
      - description: 请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.DictEditReq'
      produces:
      - application/json
      responses:
        "200":
          description: 响应成功
          schema:
            allOf:
            - $ref: '#/definitions/baseModel.ResBody'
            - properties:
                data:
                  type: boolean
              type: object
      security:
      - Token: []
      summary: 字典编辑
      tags:
      - 数据字典
  /plat/dict/get:
    post:
      consumes:
      - application/json
      description: 查询字典详情
      operationId: GetDict 字典详情
      parameters:
      - description: 请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/baseModel.IdReq'
      produces:
      - application/json
      responses:
        "200":
          description: 响应成功
          schema:
            allOf:
            - $ref: '#/definitions/baseModel.ResBody'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/baseModel.PageRes'
                  - properties:
                      list:
                        $ref: '#/definitions/platDb.Dict'
                    type: object
              type: object
      security:
      - Token: []
      summary: 字典详情
      tags:
      - 数据字典
  /plat/dict/nextVal:
    post:
      consumes:
      - application/json
      description: 在字典分组下读取下一个Val的建议值
      operationId: NextDictVal 字典NextVal建议
      parameters:
      - description: 请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.DictNextValReq'
      produces:
      - application/json
      responses:
        "200":
          description: 响应成功
          schema:
            allOf:
            - $ref: '#/definitions/baseModel.ResBody'
            - properties:
                data:
                  type: integer
              type: object
      security:
      - Token: []
      summary: 字典NextVal建议
      tags:
      - 数据字典
  /plat/dict/page:
    post:
      consumes:
      - application/json
      description: 查询字典分页数据
      operationId: PageDict 字典分页
      parameters:
      - description: 请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.DictPageReq'
      produces:
      - application/json
      responses:
        "200":
          description: 响应成功
          schema:
            allOf:
            - $ref: '#/definitions/baseModel.ResBody'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/baseModel.PageRes'
                  - properties:
                      list:
                        items:
                          $ref: '#/definitions/model.DictPageRes'
                        type: array
                    type: object
              type: object
      security:
      - Token: []
      summary: 字典分页
      tags:
      - 数据字典
  /plat/dict/read:
    post:
      consumes:
      - application/json
      description: 获取字典下拉列表以及关联键值Map
      operationId: ReadDict 读取字典
      parameters:
      - description: 语言，不传默认为zh-CN
        in: header
        name: Lang
        type: string
      - description: 请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.DictReadReq'
      produces:
      - application/json
      responses:
        "200":
          description: 响应成功
          schema:
            allOf:
            - $ref: '#/definitions/baseModel.ResBody'
            - properties:
                data:
                  $ref: '#/definitions/model.DictReadRes'
              type: object
      security:
      - Token: []
      summary: 读取字典
      tags:
      - 数据字典
  /plat/dict/sort:
    post:
      consumes:
      - application/json
      description: 字典分组下字典排序处理
      operationId: SortDict 字典排序处理
      parameters:
      - description: 语言，不传默认为zh-CN
        in: header
        name: Lang
        type: string
      - description: 请求
        in: body
        name: req
        required: true
        schema:
          items:
            $ref: '#/definitions/baseModel.SortReq'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 响应成功
          schema:
            allOf:
            - $ref: '#/definitions/baseModel.ResBody'
            - properties:
                data:
                  type: boolean
              type: object
      security:
      - Token: []
      summary: 排序处理
      tags:
      - 数据字典
  /plat/dictGroup/read:
    post:
      consumes:
      - application/json
      description: 获取字典分组下拉列表以及关联键值Map
      operationId: ReadDictGroup 字典分组读取
      parameters:
      - description: 语言，不传默认为zh-CN
        in: header
        name: Lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 响应成功
          schema:
            allOf:
            - $ref: '#/definitions/baseModel.ResBody'
            - properties:
                data:
                  $ref: '#/definitions/model.DictGroupReadRes'
              type: object
      security:
      - Token: []
      summary: 字典分组读取
      tags:
      - 数据字典
securityDefinitions:
  Token:
    in: header
    name: Token
    type: apiKey
swagger: "2.0"
tags:
- description: 基础开发接口
  name: 开放接口
x-tagGroups:
- name: 基础
  tags:
  - 开放接口
- name: 平台
  tags:
  - 租户管理
  - 集团部门
  - 角色配置
  - 登陆账号
  - 访问权限
  - 路由接口
  - 响应文言
  - 数据字典
